# 開発環境用のdokcer-compose
version: "3"
services:
  play-app:
    build: ./app/
    container_name: play-container
    volumes:
      # TODO:どのファイルをコンテナ内にマウントするののか
      # このプロジェクト自体をコンテナ内の/rootディレクトリにマウントする
      - ../play-vue-app:/play-vue-app
    working_dir: /play-vue-app
    command: "sbt run"
    ports:
      - "9000:9000"
    expose:
      - "9000"
    networks:
      - play-network
    tty: true
  vue-app:
    build: ./front
    container_name: vue-container
    volumes:
      # vueアプリ全部マウントする
      - ./front:/app/
    environment:
      WEBPACKER_DEV_SERVER_HOST: 0.0.0.0
    command: "npm run dev"
    ports:
      - "8080:8080"
    networks:
      - play-network
    tty: true
  db:
    image: mysql:5.7
    container_name: mysql-container
    environment:
      MYSQL_DATABASE: play-vue-app
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: rootpassword
    volumes:
      # DBデータの永続化
      - ./db/data:/var/lib/mysql
      - ./db/sql:/docker-entrypoint-initdb.d
      - ./db/my.cnf:/etc/mysql/conf.d/my/cnf
    networks:
      - play-network
    ports:
      - "3314:3306"
    expose:
      - "3306"

networks:
  play-network:
    external: true